In [46]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline 

In [47]:
import time

In [48]:
from sklearn.datasets import load_breast_cancer

In [49]:
import numpy as np

In [50]:
data=load_breast_cancer()

In [51]:
dataSets=pd.DataFrame(data.data,columns=data.feature_names)

In [52]:
dataSets['label']=data.target

In [53]:
data_x=dataSets.iloc[:,:-1]
data_y=dataSets.iloc[:,-1]

In [54]:
data_x=np.array(data_x)
data_y=np.array(data_y)

In [55]:
from sklearn.model_selection import cross_val_score

# knn时间测试

In [56]:
from sklearn.neighbors import  KNeighborsClassifier

In [57]:
clf=KNeighborsClassifier(n_neighbors=10,weights='uniform')

In [58]:
t1=time.time()
scores=cross_val_score(clf,data_x,data_y,scoring='accuracy',cv=10)
t2=time.time()

In [59]:
t2-t1

0.04339790344238281

In [60]:
scores

array([0.89473684, 0.85964912, 0.9122807 , 0.96491228, 0.96491228,
       0.92982456, 0.96491228, 0.94736842, 0.9122807 , 0.96428571])

In [61]:
scores.mean()

0.9315162907268169

# LR回归

In [62]:
from sklearn.linear_model import LogisticRegression 

In [63]:
clf=LogisticRegression(C=0.5,penalty='l2')

In [64]:
t1=time.time()
scores=cross_val_score(clf,data_x,data_y,scoring='accuracy',cv=10)
t2=time.time()

F:\Anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
F:\Anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_ms

In [65]:
scores

array([0.92982456, 0.92982456, 0.94736842, 0.92982456, 0.96491228,
       0.98245614, 0.92982456, 0.9122807 , 0.96491228, 0.96428571])

In [66]:
scores.mean()

0.9455513784461151

In [67]:
t2-t1

0.24425625801086426

# SVM

In [68]:
from sklearn.svm import SVC

In [69]:
clf = SVC(C=5,kernel='linear')

In [70]:
t1=time.time()
scores=cross_val_score(clf,data_x,data_y,scoring='accuracy',cv=10)
t2=time.time()

In [71]:
t2-t1

21.742359399795532

In [72]:
scores

array([0.98245614, 0.92982456, 0.92982456, 0.94736842, 0.96491228,
       0.98245614, 0.92982456, 0.94736842, 0.96491228, 0.96428571])

In [73]:
scores.mean()

0.9543233082706767

# 贝叶斯

In [74]:
from sklearn.naive_bayes import GaussianNB

In [75]:
clf=GaussianNB()

In [76]:
t1=time.time()
scores=cross_val_score(clf,data_x,data_y,cv=10,scoring='accuracy')
t2=time.time()

In [77]:
t2-t1

0.01296544075012207

In [78]:
scores.mean()

0.9367794486215537

In [79]:
scores

array([0.94736842, 0.87719298, 0.89473684, 0.92982456, 0.94736842,
       0.96491228, 0.92982456, 0.96491228, 0.94736842, 0.96428571])

# 随机森林

In [80]:
from sklearn.ensemble import RandomForestClassifier

In [81]:
clf = RandomForestClassifier(criterion='entropy',n_estimators=120,random_state=0)

In [82]:
t1=time.time()
scores=cross_val_score(clf,data_x,data_y,scoring='accuracy',cv=10)
t2=time.time()

In [83]:
t2-t1

2.186939239501953

In [84]:
scores

array([0.98245614, 0.92982456, 0.94736842, 0.94736842, 1.        ,
       0.98245614, 0.98245614, 0.98245614, 0.94736842, 0.98214286])

In [85]:
scores.mean()

0.9683897243107771

# XGBoost

In [86]:
import xgboost as xgb

In [87]:
model = xgb.XGBClassifier(learning_rate=0.3,n_estimators=120,gamma=0.2,max_depth=7,subsample=0.8)

In [88]:
t1=time.time()
scores=cross_val_score(model,data_x,data_y,cv=10,scoring='accuracy')
t2=time.time()

In [89]:
t2-t1

0.3080117702484131

In [90]:
scores

array([0.98245614, 0.94736842, 0.94736842, 0.98245614, 1.        ,
       1.        , 0.96491228, 1.        , 0.98245614, 1.        ])

In [91]:
scores.mean()

0.9807017543859649